### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by wjwarren** [bat-cha/gradle-plugin-git-dependencies#1]
Hi,

I'm trying out your project to set up my gradle build script with git-dependencies, but I think there is a small flaw in the readme.

To apply the plugin to the build script is says to use:

``` groovy
classpath 'org.batcha.gradle.plugins:gradle-plugin-git-dependencies:0.1'
```

This results in the following error when running the Gradle build file:

> FAILURE: Build failed with an exception.
> 
> What went wrong:
> Could not resolve all dependencies for configuration ':classpath'.
> Could not find group:org.batcha.gradle.plugins, module:gradle-plugin-git-dependencies, version:0.1.

I think the readme should instead have said:

``` groovy
classpath 'org.batcha.gradle.plugins:git-dependencies:0.1'
```

Once I had changed the build script to use that, the plugin is downloaded. This also seems to be more in line with what you've got in your [settings.gradle](https://github.com/bat-cha/gradle-plugin-git-dependencies/blob/master/settings.gradle) file.

Cheers,

Wijnand

PS: Gradle installation details below.

> Gradle 1.2
> 
> Gradle build time: Wednesday, 12 September 2012 10:46:02 o'clock UTC
> Groovy: 1.8.6
> Ant: Apache Ant(TM) version 1.8.4 compiled on May 22 2012
> Ivy: 2.2.0
> JVM: 1.6.0_39 (Sun Microsystems Inc. 20.14-b01)
> OS: Windows 7 6.1 x86

**Comment by bat-cha** [comment]
Hi Wijnand !

Thanks a lot for noticing, I've corrected the README as you've correctly find out the artifact name...

Do not hesitate if you have any other issue or suggestion...

Cheers
Bat
