### ISSUE TITLE
Maven dependency support

### ISSUE THREAD

**Issue by joemccall86** [bat-cha/gradle-plugin-git-dependencies#11]
I know, my stomach churns when I see maven too.  But not everyone can be on the gradle train yet :-).

Anyway, I'd like to add an option that marks a github dependency as 'maven', and the install step will be 'mvn install' rather than 'gradlew(.bat)' install. The function should fail fast if 'mvn' is not in the path.

**Comment by idyedov** [comment]
+1

**Comment by bat-cha** [comment]
Hi,
Good idea,should be fairly easy to configure the install step as you suggest...
I'll look into it ...

**Comment by bat-cha** [comment]
Won't add as per 0.2 change of use of this plugin. Feel free to fork from v0.1 and a dd a different 'install' step if you need it. and sorry for the time blackhole 10 months ago....
