### ISSUE TITLE
Plugin does not check out a branch correctly

### ISSUE THREAD

**Issue by darshakthakore** [bat-cha/gradle-plugin-git-dependencies#14]
Currently when i specify a git repository in the compile dependency, for example

compile( 'groupId:artifactId:${branchName}' ).ext.git = 'RepoURL'

It creates a new branch with 'branchName' but that branch always points to the origin/master. Ideally one would expect that 'branchName' to point to an existing branch in origin. With tags this works ok since tags are in detached head mode.

Seems like the branch creation logic is missing a call to the setStartPoint method.

**Comment by bat-cha** [comment]
Thanks a lot for your fix ! Really sorry for reactivity on this
