### ISSUE TITLE
Required Gradle version

### ISSUE THREAD

**Issue by wjwarren** [bat-cha/gradle-plugin-git-dependencies#2]
Hello,

I was wondering what the required Gradle version is to use this plugin? I'm using 1.2 as it is the required version for the [Android Gradle plugin](http://tools.android.com/tech-docs/new-build-system/using-the-new-build-system). 
From your build.gradle file I take that the required version is 1.3?

``` groovy
task wrapper(type: Wrapper) { gradleVersion = '1.3' }
```

Is there any possibility for you to support 1.2 as well?

Thanks again,

Wijnand

**Comment by bat-cha** [comment]
Hello, I'm using 1.3 in the wrapper tasks only, I'll check but it should support earlier version too as I m only relying on the gradle wrapper (gradlew or gradlew.bat) and the maven plugin to install the git dependencies to your local maven repo... I'll check and confirm....

**Comment by bat-cha** [comment]
Ok I've just checked using this branch on this dummy project:

https://github.com/bat-cha/dummy-java-project-b/tree/gradle1.2

and it worked fine so I guess the plugin supports any gradle version as long as they are compatible with the wrapper and maven plugin (that should be used in the dependencies....)

Do not hesitate to open more issues if you have any !
Thanks again
Bat

**Comment by wjwarren** [comment]
Great thanks! I guess it is an issue with the set up of my dependency.
(I was about to comment that your testProject built just fine.)

**Comment by wjwarren** [comment]
Actually, I'm not too sure about it anymore. 
I removed the local Maven repo (.m2\repository\org\batcha) and after that it seems to fail. 

> :resolveGitDependencies
> :compileJava
> 
> FAILURE: Build failed with an exception.
> 
> What went wrong:
> Could not resolve all dependencies for configuration ':compile'.
> Could not find group:org.batcha, module:dummy-project-a, version:4.2.
>  Required by:
>      org.batcha.gradle.plugins:testProject:1.0

The repo at that point has, however, been recreated. 

When you run the script again, it succeeds.

**Comment by bat-cha** [comment]
Hello Wijnand,

I've indeed been able to reproduce this, it appears that sometimes the install to mavenLocal is not yet finished but gradle go on to the next task and failed. 
I've opened an issue #3 and already have commited fix for it... 
I'll notify as soon as it is available on maven central, in the mean time if you have cloned the repo, you can do ./gradlew install to use the latest version and it should solve your problem

**Comment by wjwarren** [comment]
Thanks again! :+1:
