### ISSUE TITLE
version 0.1 replaced in maven central

### ISSUE THREAD

**Issue by idyedov** [bat-cha/gradle-plugin-git-dependencies#21]
It seems that 0.2 was released under 0.1 tag in maven central, overwriting the previous version

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.batcha.gradle.plugins%22%20AND%20a%3A%22git-dependencies%22

**Comment by bat-cha** [comment]
oops... sorry for that... I've changed the way I was publishing to maven central and looks ike there was indeed an overwrite....
I ll fix this asap

**Comment by bat-cha** [comment]
I've republished the 0.1 artifacts from the 0.1 tag... I'll let you know when maven central has refreshed  ...

**Comment by bat-cha** [comment]
https://oss.sonatype.org/content/repositories/releases/org/batcha/gradle/plugins/git-dependencies/0.1/

**Comment by idyedov** [comment]
thanks for the quick fix
