### ISSUE TITLE
Build process assumes current directory is in your $PATH

### ISSUE THREAD

**Issue by epierce** [bat-cha/gradle-plugin-git-dependencies#5]
If you do not have 'the current directory (.) in your $PATH environment variable, building dependencies fails with:

```
Cannot run program "gradlew" (in directory "/Users/epierce/src/MessageServiceWorker/MessageServiceWorkerJobs/build/git-dependencies/GoogleAppsClient"): error=2, No such file or directory
```

The obvious workaround is just to run `export PATH=$PATH:.`, but if you change the call to `gradlew` to `./gradlew`  in ResolveGitDependenciesTask.groovy, it will work regardless of what is in the user's $PATH

**Comment by bat-cha** [comment]
Hi,

Thanks for reporting this issue, I've commited the fix dd28e8d and will upload to mavenCentral later, you can locally build the plugin and install it to your local maven to solve your issue right away...

PS: do not hesitate to open issues for any suggestion/ideas, I would like to deliver a v0.2 which would be maybe more verbose and with more options so suggestions more than welcome
