### ISSUE TITLE
Do not call gradlew on dependency when it does not exist

### ISSUE THREAD

**Issue by lptr** [bat-cha/gradle-plugin-git-dependencies#6]
I'm trying to get the plugin to download a dependency that is not a Gradle project itself. It works fine, but then it tries to run `./gradlew` and it fails. Can the plugin check if `gradlew` actually exists in the project before calling it?

**Comment by bat-cha** [comment]
Hello,
handling this case is something I plan to add however I would be interested to get more details on your use case, since without gradlew in the dependency, the plugin won't be able to install it on your local maven and therefore resolve it later like any other dependencies...
Could you describe a little bit more what you would need ?
Thanks

**Comment by lptr** [comment]
What I'd like to do is basically checkout a certain revision of a Git repo. It contains some Python stuff that I want to run during my build. The tool itself has nothing to do with Gradle.

The repo I'm trying to check out is this one: https://github.com/kripken/emscripten (if you want test, maybe it's better to do it with something else, because it's big).

**Comment by bat-cha** [comment]
Ok in this case you might want to use this plugin instead https://github.com/ajoberstar/gradle-git, and write a task to clone your repository where you want.
Cheers

**Comment by lptr** [comment]
This is of course a possibility, but it means that I need to do several steps instead of doing something like this:

```
dependencies {
    emcc(group: "org.emscripten", name: "emscripten", version: "$emscripten_version").ext.git = "https://github.com/kripken/emscripten.git"
}
```

The only thing I'm missing here is the ability to _not_ run `gradlew` after the checkout.

**Comment by bat-cha** [comment]
Ok, I'll check and log info in case gradlew is not found so that build can continue
however because your dependency is defined under 

``` groovy
dependencies {...}
```

the build might fail later on if this dependency cannot be resolved...

**Comment by bat-cha** [comment]
I've commited a fix and released the updated version on maven Central (it might take some time to refresh..) 
If you're in a hurry, you can use a local version of the plugin by cloning it, and running

``` groovy
gradlew install
```

then add mavenLocal to your buildscript dependencies

``` groovy
apply plugin: 'git-dependencies'

buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath 'org.batcha.gradle.plugins:git-dependencies:0.1'
    }
}
```

**Comment by lptr** [comment]
Thanks for this extremely quick response! :)
