### ISSUE TITLE
password protected git repository

### ISSUE THREAD

**Issue by walterra** [bat-cha/gradle-plugin-git-dependencies#7]
Do you support password protected repositories (or authorization via key auth) somehow?

When trying to define a password protected git repository as a dependency, I get the following error:

```
Execution failed for task ':resolveGitDependencies'.
> <http://path-to-repository/>: not authorized
```

I tried to add the user/password like

```
http://username:password@path/repository.git
```

Also tried via SSH + key auth like

```
ssh://git@path/repository.git
```

However, even when specifing the SSH version, the error message still contains the http-link.

**Comment by walterra** [comment]
I was able to get a password protected dependency now via ssh+keyauth. Had to delete the 'git-dependencies' folder in 'build', seemed like sort of a caching problem.

**Comment by UnquietCode** [comment]
I encountered this as well. Probably the cache needs to be thrown out if the build script has changed, such as to change the repository URL.
